# --- LobbyPro Configuration File --- #

# Change the default lobby location.
lobby-location:
  World-name: World
  X: 1
  Y: 4
  Z: 1
  Yaw: 1
  Pitch: 1

# To send a join message when a player joins the server.
enable-join-message: true

# To change the message send to the player on server join.
join-message: "Welcome to the server."

# To clean the inventory on server join.
join-clear-inventory: true

# To teleport the player to the lobby/spawn location.
join-spawn: true

# To disable the player fall damage.
disable-fall-damage: true

# To disable the player hunger.
disable-hunger: true

# To disable the weather from changing.
disable-weather-change: true

# To disable tnt from exploding.
disable-tnt-explosion: true

# To disable lava damage for players.
disable-lava-damage: true

# To disable fire damage for players.
disable-fire-damage: true

# To disable players from moving items in inventory.
disable-item-move: true

# To disable players from swapping items in their inventory. (Except if they're in game-mode creative, or are op.)
disable-item-swap: true

# To disable players from picking up items.
disable-item-pick-up: true

# To disable players from placing blocks.
disable-block-placing: true

# To disable players from breaking blocks.
disable-block-breaking: true

